apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.env }}-{{ .Values.app }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: {{ .Values.env }}-{{ .Values.app }}
  namespace: {{ .Values.env }}-{{ .Values.app }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: {{ .Values.api.port }}
    protocol: {{ .Values.api.protocol }}
    targetPort: {{ .Values.api.port }}
  selector:
    app: {{ .Values.env }}-{{ .Values.app }}
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}